[cosmic-ray]
module-path = "openunderstand/metrics/max_nesting.py"
timeout = 10.0
excluded-modules = []
test-command = ".venv/Scripts/python.exe -m pytest tests -q"

[cosmic-ray.distributor]
name = "local"
